export const DARK_BLUE = '#1F4E79'
export const BLUE = '#00AEEF'
export const DARK_GRAY = '#999999'
export const MEDIUM_GRAY = '#00000029'
export const LIGHT_GRAY = '#EFEFEF'
export const WHITE = '#FFFFFF'